name: Deploy Worker
on:
  push:
    branches:
      - master
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: worker
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build Project
        run: bun run build
      - name: Run Tests
        run: bun test --coverage
      - name: Migrate Database
        run: bun run db:migrate
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: bun
          vars: |
            VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
